//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systeme_GS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public string Nom_Utilisateur { get; set; }
        public string Mot_De_Passe { get; set; }
    }
}
